package com.kenny.demo.distrilock.entity;

import java.io.Serializable;
import java.util.Date;

import lombok.ToString;

@ToString(exclude="id") 
public class Order implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7884870317439050915L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.good_name
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    private String goodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.consumer
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    private String consumer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.good_name
     *
     * @return the value of order.good_name
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.good_name
     *
     * @param goodName the value for order.good_name
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.consumer
     *
     * @return the value of order.consumer
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    public String getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.consumer
     *
     * @param consumer the value for order.consumer
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    public void setConsumer(String consumer) {
        this.consumer = consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated Sun Nov 10 15:45:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}